title: Rafagamedev
subtitle: Technical Artist
email: rpadiper@gmail.com
logo: /assets/images/rafa_pfp.jpeg
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Technical Artist who specializes in Rendering, Simulation, Tools
  and the Art Pipeline. I also make games! 
twitter_username: rafagamedev
github_username: rafapp
# Mint: #7cffc5
minimal_mistakes_skin: neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rafael Padilla Perez"
  avatar : "/assets/images/headshot.jpeg"
  bio    : "Disney College Program Intern. Technical Artist: Rendering, Simulation, Tools and the Art Pipeline. I also make games!"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/RafaGamedev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rafapp"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rafaelpadillaperez/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/RafaGamedev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Rafapp"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rafaelpadillaperez/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
